const enum MIMEType {
  TEXT_PLAIN = 'text/plain',
  TEXT_HTML = 'text/html',
  TEXT_CSS = 'text/css',
  TEXT_JS = 'text/javascript',
  TEXT_XML = 'text/xml',
  IMAGE_JPEG = 'image/jpeg',
  IMAGE_PNG = 'image/png',
  IMAGE_GIF = 'image/gif',
  IMAGE_SVG = 'image/svg+xml',
  IMAGE_WEBP = 'image/webp',
  APPLICATION_JSON = 'application/json',
  APPLICATION_XML = 'application/xml',
  APPLICATION_PDF = 'application/pdf',
  APPLICATION_MSWORD = 'application/msword',
  APPLICATION_EXCEL = 'application/vnd.ms-excel',
  APPLICATION_WORD_OPENXML = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  APPLICATION_EXCEL_OPENXML = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  APPLICATION_ZIP = 'application/zip',
  APPLICATION_RAR = 'application/x-rar-compressed',
  APPLICATION_OCTET_STREAM = 'application/octet-stream',
  AUDIO_MPEG = 'audio/mpeg',
  AUDIO_OGG = 'audio/ogg',
  AUDIO_WAV = 'audio/wav',
  VIDEO_MP4 = 'video/mp4',
  VIDEO_WEBM = 'video/webm',
  VIDEO_OGG = 'video/ogg',
  MULTIPART_FORM_DATA = 'multipart/form-data',
  APPLICATION_FORM_URLENCODED = 'application/x-www-form-urlencoded',
}
export const mimeTypesExtensions: { [id: string]: string } = {
  [MIMEType.TEXT_PLAIN]: '.txt',
  [MIMEType.APPLICATION_PDF]: '.pdf',
  [MIMEType.IMAGE_JPEG]: '.jpg',
  [MIMEType.IMAGE_PNG]: '.png',
  [MIMEType.TEXT_CSS]: '.css',
  [MIMEType.APPLICATION_JSON]: '.json',
};
